Change - push Travis build artifacts to Dropbox

diff --git a/builds/utilities/ci/travis/after_script b/builds/utilities/ci/travis/after_script
--- a/builds/utilities/ci/travis/after_script
+++ b/builds/utilities/ci/travis/after_script
@@ -3,13 +3,14 @@
 # Travis build [after_script] procedures
 #
 #  Trevor SANDY <trevor.sandy@gmail.com>
-#  Last Update: March 13, 2018
+#  Last Update: March 20, 2018
 #  Copyright (c) 2017 - 2018 by Trevor SANDY
 #
 cd $LP3D_BUILD_FOLDER
 # macOS build check...
-echo "- verify LPub3D.app bundle..."
+
 if [[ "$TRAVIS_OS_NAME" = "osx" && "$LP3D_COMPILE_SOURCE" = "true" && -z "$LP3D_BUILD_PKG" ]]; then
+  echo "- verify LPub3D.app bundle..."
   # run otool -L on LPub3D.app...
   if [ -d "mainApp/64bit_release/LPub3D.app" ]; then
     otool -L mainApp/64bit_release/LPub3D.app/Contents/MacOS/LPub3D 2>/dev/null
@@ -35,8 +36,9 @@ fi
 cd $LP3D_BUILD_FOLDER
 
 # Gather up and move build artefacts and logs to releases directory
-if [[ "$LP3D_BUILD_PKG" = "yes" && "$LP3D_COMPILE_SOURCE" = "" && "$LP3D_DEPLOY_PACKAGES" = "" ]]; then
+if [[ "$LP3D_BUILD_PKG" = "yes" && -z "$LP3D_COMPILE_SOURCE" && -z "$LP3D_BUILD_STORAGE" && -z "$LP3D_DEPLOY_PACKAGES" ]]; then
   if [ "$TRAVIS_OS_NAME" = "linux" ]; then
+    echo "Capturing Docker-generated assets..."
     if [ "$LP3D_BUILD_ARCH2017" = "true" ]; then
       file_DPkg=$(find $LP3D_COMPOSE_DIR -name LPub3D-${LP3D_APP_VERSION_LONG}*.pkg.tar.xz -type f);
       file_UPkg=$(find $LP3D_COMPOSE_DIR -name LPub3D-UpdateMaster_${LP3D_VERSION}*.pkg.tar.xz -type f);
@@ -52,30 +54,41 @@ if [[ "$LP3D_BUILD_PKG" = "yes" && "$LP3D_COMPILE_SOURCE" = "" && "$LP3D_DEPLOY_
     file_Logs=$(find $LP3D_COMPOSE_DIR -name *.log -type f);
   fi;
   if [ "$LP3D_BUILD_MACOS" = "true" ]; then
+    echo "Capturing macOS-generated assets..."
     file_DPkg=$(find $DmgBuildPath/DMGS -name LPub3D-${LP3D_APP_VERSION_LONG}*.dmg -type f);
     file_UPkg=$(find $DmgBuildPath/DMGS -name LPub3D-UpdateMaster_${LP3D_VERSION}*.dmg -type f);
-    file_Logs=$(find $DmgBuildPath -name *.log -type f);
+    file_Logs=$(find $DmgBuildPath/lpub3d -name CreateDmg.sh.log -type f);
+    [ -n "$file_Logs" ] && cp -f $file_Logs $LP3D_LOGS_DIR || echo "ERROR - Logs folder empty, nothing copied";
+    file_Logs=$(find $DmgBuildPath -name CreateRenderers.sh*.log -type f);
   fi;
   if [ "$LP3D_BUILD_APPIMAGE" = "true" ]; then
+    echo "Capturing AppImage-generated assets..."
     file_DPkg=$(find $AppImageBuildPath/AppImage -name LPub3D-${LP3D_APP_VERSION_LONG}*.AppImage -type f);
     file_UPkg=$(find $AppImageBuildPath/AppImage -name LPub3D-UpdateMaster_${LP3D_VERSION}*.AppImage -type f);
-    file_Logs=$(find $WD -name *.log -type f);
+    file_Logs=$(find ${LP3D_BUILD_FOLDER} -name CreateAppImage.log -type f);
+    [ -n "$file_Logs" ] && cp -f $file_Logs $LP3D_LOGS_DIR || echo "ERROR - Logs folder empty, nothing copied";
+    file_Logs=$(find ${LP3D_3RD_BUILD_FOLDER} -name CreateRenderers.sh*.log -type f);
   fi;
-  cp -f $file_Logs $LP3D_LOGS_DIR;
-  cp -f $file_UPkg $LP3D_UPDATE_ASSETS;
-  cp -f $file_DPkg $LP3D_DOWNLOAD_ASSETS;
+  [ -n "$file_Logs" ] && cp -f $file_Logs $LP3D_LOGS_DIR || echo "ERROR - Logs folder empty, nothing copied";
+  [ -n "$file_UPkg" ] && cp -f $file_UPkg $LP3D_UPDATE_ASSETS || echo "ERROR - Update assets folder empty, nothing copied";
+  [ -n "$file_DPkg" ] && cp -f $file_DPkg $LP3D_DOWNLOAD_ASSETS || echo "ERROR - Download assets folder empty, nothing copied";
   echo "Release Files:" && find $LP3D_RELEASES_DIR -type f;
-  # Upload assets to Dropbox for temp storage
+
+  # Set release or build Dropbox storage path
   if [ "$LP3D_DEPLOY_PKG" = "yes" ]; then
-    if [ -f "/tmp/.dropbox_oauth" ]; then
-      chmod +x "${LP3D_CI_DIR}/dropbox_uploader.sh";
-      ./"${LP3D_CI_DIR}/dropbox_uploader.sh" mkdir "$LP3D_DROPBOX_RELEASES_DIR";
-      ./"${LP3D_CI_DIR}/dropbox_uploader.sh" upload "$LP3D_LOGS_DIR" "$LP3D_DROPBOX_RELEASES_DIR"/;
-      ./"${LP3D_CI_DIR}/dropbox_uploader.sh" upload "$LP3D_UPDATE_ASSETS" "$LP3D_DROPBOX_RELEASES_DIR"/;
-      ./"${LP3D_CI_DIR}/dropbox_uploader.sh" upload "$LP3D_DOWNLOAD_ASSETS" "$LP3D_DROPBOX_RELEASES_DIR"/;
-      ./"${LP3D_CI_DIR}/dropbox_uploader.sh" list "$LP3D_DROPBOX_RELEASES_DIR";
-    else
-      echo "ERROR - /tmp/.dropbox_oauth token file not found - cannot perform upload";
-    fi;
+    LP3D_DROPBOX_DIR="$LP3D_DROPBOX_RELEASES_DIR";
+  else
+    LP3D_DROPBOX_DIR="$LP3D_DROPBOX_BUILDS_DIR";
+  fi;
+  # Upload assets to Dropbox for temp storage
+  if [ -f "/tmp/.dropbox_oauth" ]; then
+    chmod +x "${LP3D_CI_DIR}/dropbox_uploader.sh";
+    ./"${LP3D_CI_DIR}/dropbox_uploader.sh" mkdir "$LP3D_DROPBOX_DIR";
+    ./"${LP3D_CI_DIR}/dropbox_uploader.sh" upload "$LP3D_LOGS_DIR" "$LP3D_DROPBOX_DIR"/;
+    ./"${LP3D_CI_DIR}/dropbox_uploader.sh" upload "$LP3D_UPDATE_ASSETS" "$LP3D_DROPBOX_DIR"/;
+    ./"${LP3D_CI_DIR}/dropbox_uploader.sh" upload "$LP3D_DOWNLOAD_ASSETS" "$LP3D_DROPBOX_DIR"/;
+    ./"${LP3D_CI_DIR}/dropbox_uploader.sh" list "$LP3D_DROPBOX_DIR";
+  else
+    echo "ERROR - /tmp/.dropbox_oauth token file not found - cannot perform upload";
   fi;
 fi
diff --git a/builds/utilities/ci/travis/prepare_store b/builds/utilities/ci/travis/prepare_store
--- a/builds/utilities/ci/travis/prepare_store
+++ b/builds/utilities/ci/travis/prepare_store
@@ -3,16 +3,25 @@
 # Travis build [prepare_store] procedures
 #
 #  Trevor SANDY <trevor.sandy@gmail.com>
-#  Last Update: December 31, 2017
+#  Last Update: March 17, 2017
 #  Copyright (c) 2017 - 2018 by Trevor SANDY
 #
 cd $LP3D_BUILD_FOLDER
 
-if [ -f "/tmp/.dropbox_oauth" ]; then
-  chmod +x "${LP3D_CI_DIR}/dropbox_uploader.sh";
-  echo $(./"${LP3D_CI_DIR}"/dropbox_uploader.sh list "$LP3D_DROPBOX_RELEASES_DIR") | grep -w 'DONE' \
-  && echo "Deleting old Dropbox store folder '$LP3D_DROPBOX_RELEASES_DIR'..." \
-  && ./"${LP3D_CI_DIR}/dropbox_uploader.sh" delete "$LP3D_DROPBOX_RELEASES_DIR" || true
-else
-  echo "ERROR - /tmp/.dropbox_oauth token file not found - cannot perform delete.";
+if [ "$LP3D_BUILD_STORAGE" = "true" ]; then
+  LP3D_DROPBOX_DIR="$LP3D_DROPBOX_BUILDS_DIR";
+elif [ "$LP3D_DEPLOY_PACKAGES" = "true" ]; then
+  LP3D_DROPBOX_DIR="$LP3D_DROPBOX_RELEASES_DIR";
+fi;
+
+if [ -n "$LP3D_DROPBOX_DIR" ]; then
+  # Remove previous Dropbox storage paths
+  if [ -f "/tmp/.dropbox_oauth" ]; then
+    chmod +x "${LP3D_CI_DIR}/dropbox_uploader.sh";
+    echo $(./"${LP3D_CI_DIR}"/dropbox_uploader.sh list "$LP3D_DROPBOX_DIR") | grep -w 'DONE' \
+    && echo "Deleting previous Dropbox store folder '$LP3D_DROPBOX_DIR'..." \
+    && ./"${LP3D_CI_DIR}/dropbox_uploader.sh" delete "$LP3D_DROPBOX_DIR" || true
+  else
+    echo "ERROR - /tmp/.dropbox_oauth token file not found - cannot perform delete.";
+  fi;
 fi;
