Mac: update create-dmg script from 1.0.9 to 1.2.1 #761

diff --git a/builds/utilities/dmg-utils/create-dmg b/builds/utilities/dmg-utils/create-dmg
--- a/builds/utilities/dmg-utils/create-dmg
+++ b/builds/utilities/dmg-utils/create-dmg
@@ -4,13 +4,18 @@
 
 # Bail out on any unhandled errors
 set -e;
+# Any command that exits with non-zero code will cause the pipeline to fail
+set -o pipefail;
 
-CDMG_VERSION='1.0.9-SNAPSHOT'
+CDMG_VERSION='1.2.1'
 
 # The full path to the "support/" directory this script is using
 # (This will be set up by code later in the script.)
 CDMG_SUPPORT_DIR=""
 
+OS_FULL_VERSION="$(sw_vers | sed -n 2p | cut -d : -f 2 | tr -d '[:space:]' | cut -c1-)"
+OS_MAJOR_VERSION="$(echo $OS_FULL_VERSION | cut -d . -f 1)"
+OS_MINOR_VERSION="$(echo $OS_FULL_VERSION | cut -d . -f 2)"
 WINX=10
 WINY=60
 WINW=500
@@ -18,15 +23,40 @@ WINH=350
 ICON_SIZE=128
 TEXT_SIZE=16
 FORMAT="UDZO"
+FILESYSTEM="HFS+"
 ADD_FILE_SOURCES=()
 ADD_FILE_TARGETS=()
 IMAGEKEY=""
 HDIUTIL_VERBOSITY=""
 SANDBOX_SAFE=0
+BLESS=0
 SKIP_JENKINS=0
+MAXIMUM_UNMOUNTING_ATTEMPTS=3
+SIGNATURE=""
+NOTARIZE=""
 
 function pure_version() {
 	echo "$CDMG_VERSION"
+}
+
+function hdiutil_detach_retry() {
+	# Unmount
+	unmounting_attempts=0
+	until
+		echo "Unmounting disk image..."
+		(( unmounting_attempts++ ))
+		hdiutil detach "$1"
+		exit_code=$?
+		(( exit_code ==  0 )) && break            # nothing goes wrong
+		(( exit_code != 16 )) && exit $exit_code  # exit with the original exit code
+		# The above statement returns 1 if test failed (exit_code == 16).
+		#   It can make the code in the {do... done} block to be executed
+	do
+		(( unmounting_attempts == MAXIMUM_UNMOUNTING_ATTEMPTS )) && exit 16  # patience exhausted, exit with code EBUSY
+		echo "Wait a moment..."
+		sleep $(( 1 * (2 ** unmounting_attempts) ))
+	done
+	unset unmounting_attempts
 }
 
 function version() {
@@ -48,8 +78,6 @@ Options:
 	  set volume name (displayed in the Finder sidebar and window title)
   --volicon <icon.icns>
 	  set volume icon
-  --dmgicon <pic.png>"
-	  set dmg file icon (create dmg icon from png file)
   --background <pic.png>
 	  set folder background image (provide png, gif, or jpg)
   --window-pos <x> <y>
@@ -73,7 +101,13 @@ Options:
   --no-internet-enable
 	  disable automatic mount & copy
   --format <format>
-	  specify the final image format (default is UDZO)
+	  specify the final disk image format (UDZO|UDBZ|ULFO|ULMO) (default is UDZO)
+  --filesystem <filesystem>
+	  specify the disk image filesystem (HFS+|APFS) (default is HFS+, APFS supports macOS 10.13 or newer)
+  --encrypt
+	  enable encryption for the resulting disk image (AES-256 - you will be prompted for password)
+  --encrypt-aes128
+	  enable encryption for the resulting disk image (AES-128 - you will be prompted for password)
   --add-file <target_name> <file>|<folder> <x> <y>
 	  add additional file or folder (can be used multiple times)
   --disk-image-size <x>
@@ -82,17 +116,42 @@ Options:
 	  execute hdiutil in verbose mode
   --hdiutil-quiet
 	  execute hdiutil in quiet mode
+  --bless
+	  bless the mount folder (deprecated, needs macOS 12.2.1 or older)
+  --codesign <signature>
+	  codesign the disk image with the specified signature
+  --notarize <credentials>
+	  notarize the disk image (waits and staples) with the keychain stored credentials
   --sandbox-safe
-	  execute hdiutil with sandbox compatibility and do not bless
-  --rez <rez_path>
-	  use custom path to Rez tool
+	  execute hdiutil with sandbox compatibility and do not bless (not supported for APFS disk images)
+  --skip-jenkins
+	  skip Finder-prettifying AppleScript, useful in Sandbox and non-GUI environments
   --version
-	    show create-dmg version number
+	  show create-dmg version number
   -h, --help
-	    display this help screen
+	  display this help screen
 
 EOHELP
 	exit 0
+}
+
+# factors can cause interstitial disk images to contain more than a single
+# partition - expand the hunt for the temporary disk image by checking for
+# the path of the volume, versus assuming its the first result (as in pr/152).
+function find_mount_dir() {
+	local dev_name="${1}"
+
+	>&2 echo "Searching for mounted interstitial disk image using ${dev_name}... "
+	# enumerate up to 9 partitions
+	for i in {1..9}; do
+		# attempt to find the partition
+		local found_dir
+		found_dir=$(hdiutil info | grep -E --color=never "${dev_name}" | head -${i} | awk '{print $3}' | xargs)
+		if [[ -n "${found_dir}" ]]; then
+				echo "${found_dir}"
+				return 0
+		fi
+	done
 }
 
 # Argument parsing
@@ -106,10 +165,6 @@ while [[ "${1:0:1}" = "-" ]]; do
 		--volicon)
 			VOLUME_ICON_FILE="$2"
 			echo "    __VOLUME_ICON_FILE................: ${VOLUME_ICON_FILE}"
-			shift; shift;;
-		--dmgicon)
-			DMG_ICON_FILE="$2"
-			echo "    __DMG_ICON_FILE...................: ${DMG_ICON_FILE}"
 			shift; shift;;
 		--background)
 			BACKGROUND_FILE="$2"
@@ -138,7 +193,8 @@ while [[ "${1:0:1}" = "-" ]]; do
 			echo "    __WINDOW_SIZE WINW, WINH..........: ${WINW}, ${WINH}"
 			shift; shift; shift;;
 		--icon)
-			POSITION_CLAUSE="${POSITION_CLAUSE}set position of item \"$2\" to {$3, $4}"
+			POSITION_CLAUSE="${POSITION_CLAUSE}set position of item \"$2\" to {$3, $4}
+			"
 			echo "    __ICON_POSITION_CLAUSE............: ${ICON_POSITION_CLAUSE}"
 			shift; shift; shift; shift;;
 		--hide-extension)
@@ -157,7 +213,7 @@ while [[ "${1:0:1}" = "-" ]]; do
 			QL_CLAUSE="set position of item \"QuickLook\" to {$2, $3}
 			"
 			echo "    __QL_LINK.........................: ${QL_LINK}"
-			echo "    __APPLICATION_CLAUSE..............: ${APPLICATION_CLAUSE}"
+			echo "    __APPLICATION_CLAUSE..............: ${QL_CLAUSE}"
 			shift; shift; shift;;
 		--app-drop-link)
 			APPLICATION_LINK=$2
@@ -178,14 +234,30 @@ while [[ "${1:0:1}" = "-" ]]; do
 			FORMAT="$2"
 			echo "    __FORMAT..........................: ${FORMAT}"
 			shift; shift;;
+		--filesystem)
+			FILESYSTEM="$2"
+			echo "    __FILESYSTEM......................: ${FILESYSTEM}"
+			shift; shift;;
+		--encrypt)
+			ENABLE_ENCRYPTION=1
+			AESBITS=256
+			echo "    __ENABLE_ENCRYPTION...............: ${ENABLE_ENCRYPTION}"
+			echo "    __AESBITS.........................: ${AESBITS}"
+			shift;;
+		--encrypt-aes128)
+			ENABLE_ENCRYPTION=1
+			AESBITS=128
+			echo "    __ENABLE_ENCRYPTION...............: ${ENABLE_ENCRYPTION}"
+			echo "    __AESBITS.........................: ${AESBITS}"
+			shift;;
 		--add-file | --add-folder)
 			ADD_FILE_TARGETS+=("$2")
 			ADD_FILE_SOURCES+=("$3")
 			POSITION_CLAUSE="${POSITION_CLAUSE}
 			set position of item \"$2\" to {$4, $5}
 			"
-			echo "    __ADD_FILE_TARGETS................: ${ICON_CUSTOM_NAME}"
-			echo "    __ADD_FILE_SOURCES................: ${ICON_CUSTOM_FILE}"
+			echo "    __ADD_FILE_TARGETS................: ${ADD_FILE_TARGETS}"
+			echo "    __ADD_FILE_SOURCES................: ${ADD_FILE_SOURCES}"
 			echo "    __POSITION_CLAUSE.................: ${POSITION_CLAUSE}"
 			shift; shift; shift; shift; shift;;
 		--disk-image-size)
@@ -200,12 +272,24 @@ while [[ "${1:0:1}" = "-" ]]; do
 			HDIUTIL_VERBOSITY='-quiet'
 			echo "    __HDIUTIL_VERBOSITY...............: ${HDIUTIL_VERBOSITY}"
 			shift;;
+		--codesign)
+			SIGNATURE="$2"
+			echo "    __SIGNATURE.......................: ${SIGNATURE}"
+			shift; shift;;
+		--notarize)
+			NOTARIZE="$2"
+			echo "    __NOTARIZE........................: ${NOTARIZE}"
+			shift; shift;;
 		--sandbox-safe)
 			SANDBOX_SAFE=1
 			echo "    __SANDBOX_SAFE....................: ${SANDBOX_SAFE}"
 			shift;;
+		--bless)
+			BLESS=1
+			echo "    __BLESS...........................: ${BLESS}"
+			shift;;
 		--rez)
-			REZ_PATH="$2"
+			echo "REZ is no more directly used. You can remove the --rez argument."
 			echo "    __REZ_PATH........................: ${REZ_PATH}"
 			shift; shift;;
 		--skip-jenkins)
@@ -221,8 +305,12 @@ while [[ "${1:0:1}" = "-" ]]; do
 			IMAGEKEY="-imagekey zlib-level=9";;
 		UDBZ)
 			IMAGEKEY="-imagekey bzip2-level=9";;
+		ULFO)
+			;;
+		ULMO)
+			;;
 		*)
-			echo >&2 "Unknown format: $FORMAT"
+			echo >&2 "Unknown disk image format: $FORMAT"
 			exit 1;;
 	esac
 done
@@ -235,20 +323,37 @@ fi
 DMG_PATH="$1"
 SRC_FOLDER="$(cd "$2" > /dev/null; pwd)"
 
+# Argument validation checks
+
+if [[ "${DMG_PATH: -4}" != ".dmg" ]]; then
+	echo "Output file name must end with a .dmg extension. Run 'create-dmg --help' for help."
+	exit 1
+fi
+
+if [[ "${FILESYSTEM}" != "HFS+" ]] && [[ "${FILESYSTEM}" != "APFS" ]]; then
+	echo "Unknown disk image filesystem: ${FILESYSTEM}. Run 'create-dmg --help' for help."
+	exit 1
+fi
+
+if [[ "${FILESYSTEM}" == "APFS" ]] && [[ ${SANDBOX_SAFE} -eq 1 ]]; then
+	echo "Creating an APFS disk image that is sandbox safe is not supported."
+	exit 1
+fi
+
 # Main script logic
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 DMG_DIRNAME="$(dirname "$DMG_PATH")"
 DMG_DIR="$(cd "$DMG_DIRNAME" > /dev/null; pwd)"
 DMG_NAME="$(basename "$DMG_PATH")"
-DMG_TEMP_NAME="$DMG_DIR/rw.${DMG_NAME}"
+DMG_TEMP_NAME="$DMG_DIR/rw.$$.${DMG_NAME}"
 
 # Detect where we're running from
 
-repo_sentinel_file="$SCRIPT_DIR/dmg-utils/.this-is-the-repo-sentinel-file"
-if [[ -f "$repo_sentinel_file" ]]; then
+sentinel_file="$SCRIPT_DIR/.this-is-the-create-dmg-repo"
+if [[ -f "$sentinel_file" ]]; then
 	# We're running from inside a repo
-	CDMG_SUPPORT_DIR="$SCRIPT_DIR/dmg-utils"
+	CDMG_SUPPORT_DIR="$SCRIPT_DIR/support"
 else
 	# We're running inside an installed location
 	bin_dir="$SCRIPT_DIR"
@@ -294,7 +399,12 @@ function blocks_to_megabytes() {
 
 function get_size() {
 	# Get block size in disk
-	bytes_size=$(du -s "$1" | sed -e 's/	.*//g')
+	if [[ $OS_MAJOR_VERSION -ge 12 ]]; then
+		bytes_size=$(du -B 512 -s "$1")
+	else
+		bytes_size=$(du -s "$1")
+	fi
+	bytes_size=$(echo $bytes_size | sed -e 's/  .*//g')
 	echo $(blocks_to_megabytes $bytes_size)
 }
 
@@ -305,8 +415,13 @@ if [[ -n "$DISK_IMAGE_SIZE" ]]; then
 fi
 
 if [[ $SANDBOX_SAFE -eq 0 ]]; then
+	if [[ "$FILESYSTEM" == "APFS" ]]; then
+		FILESYSTEM_ARGUMENTS=""
+	else
+		FILESYSTEM_ARGUMENTS="-c c=64,a=16,e=16"
+	fi
 	hdiutil create ${HDIUTIL_VERBOSITY} -srcfolder "$SRC_FOLDER" -volname "${VOLUME_NAME}" \
-		-fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDRW ${CUSTOM_SIZE} "${DMG_TEMP_NAME}"
+		-fs "${FILESYSTEM}" -fsargs "${FILESYSTEM_ARGUMENTS}" -format UDRW ${CUSTOM_SIZE} "${DMG_TEMP_NAME}"
 else
 	hdiutil makehybrid ${HDIUTIL_VERBOSITY} -default-volume-name "${VOLUME_NAME}" -hfs -o "${DMG_TEMP_NAME}" "$SRC_FOLDER"
 	hdiutil convert -format UDRW -ov -o "${DMG_TEMP_NAME}" "${DMG_TEMP_NAME}"
@@ -321,7 +436,7 @@ if [[ $SANDBOX_SAFE -eq 1 ]] && [[ ! -z "$DISK_IMAGE_SIZE_CUSTOM" ]] && [[ $DISK
 	DISK_IMAGE_SIZE=$DISK_IMAGE_SIZE_CUSTOM
 fi
 
-# Estimate the additional soruces size
+# Estimate the additional sources size
 if [[ -n "$ADD_FILE_SOURCES" ]]; then
 	for i in "${!ADD_FILE_SOURCES[@]}"; do
 		SOURCE_SIZE=$(get_size "${ADD_FILE_SOURCES[$i]}")
@@ -332,28 +447,45 @@ fi
 # Add extra space for additional resources
 DISK_IMAGE_SIZE=$(expr $DISK_IMAGE_SIZE + 20)
 
+# Make sure target image size is within limits
+MIN_DISK_IMAGE_SIZE=$(hdiutil resize -limits "${DMG_TEMP_NAME}" | awk 'NR=1{print int($1/2048+1)}')
+if [ $MIN_DISK_IMAGE_SIZE -gt $DISK_IMAGE_SIZE ]; then
+	   DISK_IMAGE_SIZE=$MIN_DISK_IMAGE_SIZE
+fi
+
 # Resize the image for the extra stuff
 hdiutil resize ${HDIUTIL_VERBOSITY} -size ${DISK_IMAGE_SIZE}m "${DMG_TEMP_NAME}"
 
 # Mount the new DMG
 
-MOUNT_DIR="/Volumes/${VOLUME_NAME}"
-
-# Unmount leftover dmg if it was mounted previously (e.g. developer mounted dmg, installed app and forgot to unmount it)
-if [[ -d "${MOUNT_DIR}" ]]; then
-	echo "Unmounting old disk image from $MOUNT_DIR..."
-	DEV_NAME=$(hdiutil info | egrep --color=never '^/dev/' | sed 1q | awk '{print $1}')
-	hdiutil detach "${DEV_NAME}"
-fi
-
 echo "Mounting disk image..."
 
-echo "Mount directory: $MOUNT_DIR"
-DEV_NAME=$(hdiutil attach -readwrite -noverify -noautoopen "${DMG_TEMP_NAME}" | egrep --color=never '^/dev/' | sed 1q | awk '{print $1}')
+MOUNT_RANDOM_PATH="/Volumes"
+if [[ $SANDBOX_SAFE -eq 1 ]]; then
+	MOUNT_RANDOM_PATH="/tmp"
+fi
+if [[ "$FILESYSTEM" == "APFS" ]]; then
+  HDIUTIL_FILTER="tail -n 1"
+else
+  HDIUTIL_FILTER="sed 1q"
+fi
+DEV_NAME=$(hdiutil attach -mountrandom ${MOUNT_RANDOM_PATH} -readwrite -noverify -noautoopen -nobrowse "${DMG_TEMP_NAME}" | grep -E --color=never '^/dev/' | ${HDIUTIL_FILTER} | awk '{print $1}')
 echo "Device name:     $DEV_NAME"
+if [[ "$FILESYSTEM" == "APFS" ]]; then
+  MOUNT_DIR=$(find_mount_dir "${DEV_NAME}")
+else
+	MOUNT_DIR=$(find_mount_dir "${DEV_NAME}s")
+fi
+if [[ -z "${MOUNT_DIR}" ]]; then
+  >&2 echo "ERROR: unable to proceed with final disk image creation because the interstitial disk image was not found."
+  >&2 echo "The interstitial disk image will likely be mounted and will need to be cleaned up manually."
+  exit 1
+fi
+
+echo "Mount dir:       $MOUNT_DIR"
 
 if [[ -n "$BACKGROUND_FILE" ]]; then
-	echo "Copying background file..."
+	echo "Copying background file '$BACKGROUND_FILE'..."
 	[[ -d "$MOUNT_DIR/.background" ]] || mkdir "$MOUNT_DIR/.background"
 	cp "$BACKGROUND_FILE" "$MOUNT_DIR/.background/$BACKGROUND_FILE_NAME"
 fi
@@ -384,6 +516,8 @@ if [[ -n "$ADD_FILE_SOURCES" ]]; then
 	done
 fi
 
+VOLUME_NAME=$(basename $MOUNT_DIR)
+
 # Run AppleScript to do all the Finder cosmetic stuff
 APPLESCRIPT_FILE=$(mktemp -t createdmg.tmp.XXXXXXXXXX)
 if [[ $SANDBOX_SAFE -eq 1 ]]; then
@@ -400,19 +534,30 @@ else
 			| perl -pe "s/APPLICATION_CLAUSE/$APPLICATION_CLAUSE/g" \
 			| perl -pe "s/HIDING_CLAUSE/$HIDING_CLAUSE/" \
 			> "$APPLESCRIPT_FILE"
-		sleep 2 # pause to workaround occasional "Can’t get disk" (-1728) issues
+
+		# pause to workaround occasional "Can’t get disk" (-1728) issues
+		ERROR_1728_WORKAROUND_SLEEP_INTERVAL=2
+		echo "Will sleep for $ERROR_1728_WORKAROUND_SLEEP_INTERVAL seconds to workaround occasions \"Can't get disk (-1728)\" issues..."
+		sleep $ERROR_1728_WORKAROUND_SLEEP_INTERVAL
+
 		echo "Running AppleScript to make Finder stuff pretty: /usr/bin/osascript \"${APPLESCRIPT_FILE}\" \"${VOLUME_NAME}\""
 		if /usr/bin/osascript "${APPLESCRIPT_FILE}" "${VOLUME_NAME}"; then
 			# Okay, we're cool
 			true
 		else
 			echo >&2 "Failed running AppleScript"
-			hdiutil detach "${DEV_NAME}"
+			hdiutil_detach_retry "${DEV_NAME}"
 			exit 64
 		fi
 		echo "Done running the AppleScript..."
 		sleep 4
 		rm "$APPLESCRIPT_FILE"
+	else
+		echo ''
+		echo "Will skip running AppleScript to configure DMG aesthetics because of --skip-jenkins option."
+		echo "This will result in a DMG without any custom background or icons positioning."
+		echo "More info at https://github.com/create-dmg/create-dmg/issues/72"
+		echo ''
 	fi
 fi
 
@@ -422,7 +567,7 @@ chmod -Rf go-w "${MOUNT_DIR}" &> /dev/null || true
 echo "Done fixing permissions"
 
 # Make the top window open itself on mount:
-if [[ $SANDBOX_SAFE -eq 0 ]]; then
+if [[ $BLESS -eq 1 && $SANDBOX_SAFE -eq 0 ]]; then
 	echo "Blessing started"
 	if [ $(uname -m) == "arm64" ]; then
 		bless --folder "${MOUNT_DIR}"
@@ -439,34 +584,55 @@ if [[ -n "$VOLUME_ICON_FILE" ]]; then
 	SetFile -a C "$MOUNT_DIR"
 fi
 
-# Unmount
-echo "Unmounting disk image..."
-hdiutil detach "${DEV_NAME}"
+# Delete unnecessary file system events log if possible
+echo "Deleting .fseventsd"
+rm -rf "${MOUNT_DIR}/.fseventsd" || true
 
-# Compress image
-echo "Compressing disk image..."
-hdiutil convert ${HDIUTIL_VERBOSITY} "${DMG_TEMP_NAME}" -format ${FORMAT} ${IMAGEKEY} -o "${DMG_DIR}/${DMG_NAME}"
-rm -f "${DMG_TEMP_NAME}"
+hdiutil_detach_retry "${DEV_NAME}"
 
-# Set dmg file icon from png input file
-if ! test -z "$DMG_ICON_FILE"; then
-	echo "Adding dmg file icon from ${DMG_ICON_FILE}..."
-	chmod +x "${CDMG_SUPPORT_DIR}/dmg-fileicon"
-	"${CDMG_SUPPORT_DIR}/dmg-fileicon" set "${DMG_DIR}/${DMG_NAME}" "${DMG_ICON_FILE}"
+# Compress image and optionally encrypt
+if [[ $ENABLE_ENCRYPTION -eq 0 ]]; then
+	echo "Compressing disk image..."
+	hdiutil convert ${HDIUTIL_VERBOSITY} "${DMG_TEMP_NAME}" -format ${FORMAT} ${IMAGEKEY} -o "${DMG_DIR}/${DMG_NAME}"
+else
+	echo "Compressing and encrypting disk image..."
+	echo "NOTE: hdiutil will only prompt a single time for a password - ensure entry is correct."
+	hdiutil convert ${HDIUTIL_VERBOSITY} "${DMG_TEMP_NAME}" -format ${FORMAT} ${IMAGEKEY} -encryption AES-${AESBITS} -stdinpass -o "${DMG_DIR}/${DMG_NAME}"
 fi
+rm -f "${DMG_TEMP_NAME}"
 
 # Adding EULA resources
 if [[ -n "${EULA_RSRC}" && "${EULA_RSRC}" != "-null-" ]]; then
 	echo "Adding EULA resources..."
-	REZ_ARG=""
-	if [[ -n "${REZ_PATH}" && "${REZ_PATH}" != "-null-" ]]; then
-		REZ_ARG="--rez ${REZ_PATH}"
+	#
+	# Use udifrez instead flatten/rez/unflatten
+	# https://github.com/create-dmg/create-dmg/issues/109
+	#
+	# Based on a thread from dawn2dusk & peterguy
+	# https://developer.apple.com/forums/thread/668084
+	#
+	EULA_RESOURCES_FILE=$(mktemp -t createdmg.tmp.XXXXXXXXXX)
+	EULA_FORMAT=$(file -b ${EULA_RSRC})
+	if [[ ${EULA_FORMAT} == 'Rich Text Format data'* ]] ; then
+		EULA_FORMAT='RTF '
 	else
-		xcode_path=$(xcode-select -p)
-		default_rez="$xcode_path/Tools/Rez"
-		REZ_ARG="--rez ${default_rez}"
+		EULA_FORMAT='TEXT'
 	fi
-	"${CDMG_SUPPORT_DIR}/licenseDMG.py" "${DMG_DIR}/${DMG_NAME}" "${EULA_RSRC}" ${REZ_ARG}
+	# Encode the EULA to base64
+	# Replace 'openssl base64' with 'base64' if Mac OS X 10.6 support is no more needed
+	# EULA_DATA="$(base64 -b 52 "${EULA_RSRC}" | sed s$'/^\(.*\)$/\t\t\t\\1/')"
+	EULA_DATA="$(openssl base64 -in "${EULA_RSRC}" | tr -d '\n' | awk '{gsub(/.{52}/,"&\n")}1' | sed s$'/^\(.*\)$/\t\t\t\\1/')"
+	# Fill the template with the custom EULA contents
+	eval "cat > \"${EULA_RESOURCES_FILE}\" <<EOF
+	$(<${CDMG_SUPPORT_DIR}/eula-resources-template.xml)
+	EOF
+	"
+	# Apply the resources
+	hdiutil udifrez -xml "${EULA_RESOURCES_FILE}" '' -quiet "${DMG_DIR}/${DMG_NAME}" || {
+		echo "Failed to add the EULA license"
+		exit 1
+	}
+	echo "Successfully added the EULA license"
 fi
 
 # Enable "internet", whatever that is
@@ -479,6 +645,32 @@ else
 		hdiutil internet-enable -yes "${DMG_DIR}/${DMG_NAME}"
 	else
 		echo "hdiutil does not support internet-enable. Note it was removed in macOS 10.15."
+	fi
+fi
+
+if [[ -n "${SIGNATURE}" && "${SIGNATURE}" != "-null-" ]]; then
+	echo "Codesign started"
+	codesign -s "${SIGNATURE}" "${DMG_DIR}/${DMG_NAME}"
+	dmgsignaturecheck="$(codesign --verify --deep --verbose=2 --strict "${DMG_DIR}/${DMG_NAME}" 2>&1 >/dev/null)"
+	if [ $? -eq 0 ]; then
+		echo "The disk image is now codesigned"
+	else
+		echo "The signature seems invalid${NC}"
+		exit 1
+	fi
+fi
+
+if [[ -n "${NOTARIZE}" && "${NOTARIZE}" != "-null-" ]]; then
+	echo "Notarization started"
+	xcrun notarytool submit "${DMG_DIR}/${DMG_NAME}" --keychain-profile "${NOTARIZE}" --wait
+	echo "Stapling the notarization ticket"
+	staple="$(xcrun stapler staple "${DMG_DIR}/${DMG_NAME}")"
+	if [ $? -eq 0 ]; then
+		echo "The disk image is now notarized"
+	else
+		echo "$staple"
+		echo "The notarization failed with error $?"
+		exit 1
 	fi
 fi
 
